name: Publish package to GitHub Packages
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14' # Adjust the Node.js version as per your project requirements
          registry-url: 'https://npm.pkg.github.com'
          scope: '@checkfirst-ltd' # Ensure correct scope for your package
      
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Compile TypeScript (adjust paths and options as needed)
      - name: Compile TypeScript
        run: npm run build  # Adjust this command based on your project's build script
      
      # Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
